CREATE FUNCTION [wpi].[fn_get_json_date] 
(
	@DATE datetime NULL = NULL
)
RETURNS bigint AS
BEGIN
    DECLARE @JSONSENDDATE BIGINT
	SET @JSONSENDDATE = DATEDIFF(DD, CAST('1970-01-01 00:00:00' AS DATETIME),ISNULL(@DATE,GETDATE()))* 86400 + DATEPART(hh,ISNULL(@DATE,GETDATE()))*3600
	SET @JSONSENDDATE  = @JSONSENDDATE  * 1000
    RETURN @JSONSENDDATE
END
